- name: Test Apache
  hosts: all
  tasks:
     - debug:
         msg: "System {{ inventory_hostname }} 
               {{ ansible_all_ipv4_addresses }} has gateway {{ ansible_default_ipv4.gateway }} 
                   with {{ ansible_python_version }}"
