- name: Test Apache
  hosts: all
  tasks:
     - debug:
         msg: "System{{ ansible_all_ipv4_addresses }} and {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }} with {{ ansible_python_version }}"
