- name: Test Apache
  hosts: all
  tasks:
     - debug:
         msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
         msg: "System {{ hostvars[groups['webservers'][0]]['ansible_eth0']['ipv4']['address'] }}"
